services:
  rtmp:
    build:
      context: .
      dockerfile: Dockerfile
    image: team9-rtmp:local
    platform: linux/amd64
    container_name: rtmp-server
    ports:
      - "1935:1935"
      - "8088:80"
    restart: unless-stopped
